[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "froster"
version = "0.12.0"
description = "Froster is a tool for easy data transfer between local file systems and AWS S3 storage."
authors = ["Victor Machado <victor.machado@hpcnow.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.34.104"
duckdb = "^0.10.2"
inquirer = "^3.2.4"
psutil = "^5.9.0"
requests = "^2.31.0"
textual = "^0.59.0"
visidata = "^3.0.2"

[tool.poetry.scripts]
froster = "froster.froster:main"
