[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "froster"
version = "0.18.1"
description = "Froster is a tool for easy data transfer between local file systems and AWS S3 storage."
authors = ["Victor Machado <victor.machado@hpcnow.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.34.119"
duckdb = "^1.0.0"
inquirer = "^3.2.4"
psutil = "^5.9.8"
requests = "^2.32.3"
textual = "^0.64.0"
visidata = "^3.0.2"
setuptools = "^70.0.0"

[tool.poetry.scripts]
froster = "froster.froster:main"
